title: RCC
 
timezone: Asia/Tokyo

theme: minima

collections:
  contents:
    output: true

defaults:
  - scope:
      path: ""
      type: "galleries"
    values:
      layout: "post"
      
  - scope:
      path: ""
    values:
      layout: "default"