theme: minima

collections:
  galleries:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      
  - scope:
      path: ""
    values:
      layout: "default"